source 'https://rubygems.org'

gem 'colored'

gem 'sass'
gem 'compass'

gem 'rake-pipeline', :git => 'https://github.com/livingsocial/rake-pipeline.git'
gem 'rake-pipeline-web-filters', :git => 'https://github.com/wycats/rake-pipeline-web-filters.git'

group :dev do
  gem 'guard'
  gem 'guard-rake'
  gem 'rb-fsevent', '~> 0.9.1'

  gem 'rack'
  gem 'rack-rewrite'
  gem 'rack-streaming-proxy'
end

group :prod do
  gem 'therubyracer'
  gem 'uglifier'
  gem 'yui-compressor'
end
